name: Lint Markdown

on:
  pull_request:
    paths:
      - README.md
      - docs/**/*.md
      - .markdownlint-cli2.jsonc
      - .github/workflows/lint-markdown.yml
  push:
    branches: [main]
    paths:
      - README.md
      - docs/**/*.md
      - .markdownlint-cli2.jsonc
      - .github/workflows/lint-markdown.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdown:
    uses: DevOpsDerek/workflows/.github/workflows/lint-markdown.yml@30f86d7d8536364b0a31de4bc66214b39e8785bb
    with:
      working-directory: .
      markdown-paths: |-
        README.md
        docs/**/*.md
    permissions:
      contents: read
