name: Lint Markdown

on:
  pull_request:
    paths:
      - README.md
      - docs/**/*.md
      - .markdownlint-cli2.jsonc
      - .github/workflows/lint-markdown.yml
  push:
    branches: [main]
    paths:
      - README.md
      - docs/**/*.md
      - .markdownlint-cli2.jsonc
      - .github/workflows/lint-markdown.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdown:
    uses: DevOpsDerek/workflows/.github/workflows/lint-markdown.yml@c4ac3847334c8944a48619ae4f3f0d622f4a074b
    with:
      working-directory: .
      markdown-paths: |
        README.md
        docs/**/*.md
    permissions:
      contents: read
